iterative tests
we can now sequence multiple _input and checks in each test

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -3,19 +3,11 @@
 set root (dirname (status filename))
 set -l error false
 
-fish "$root/tests/_run.fish" "$root/tests/_example_test.fish" (mktemp -d)
+set -l temp_dir "$(mktemp -d)"
+fish "$root/tests/_run.fish" "$root/tests/_example_test.fish" "$temp_dir"
 or begin
     echo "$root/tests/_example_test.fish has failed, but it should have succeeded" >&2
-    set error true
-end
-
-fish "$root/tests/_run.fish" "$root/tests/_broken_test.fish" (mktemp -d)
-and begin
-    echo "$root/tests/_broken_test.fish has succeeded, but it should have failed" >&2
-    set error true
-end
-
-if test "$error" = true
+    cat "$temp_dir/out" >&2
     exit 1
 end
 
@@ -33,20 +25,23 @@ for dir in $argv
         set temp_dir "$(mktemp -d)"
         if fish "$root/tests/_run.fish" "$test_file" "$temp_dir"
             if test -e "$temp_dir/broken"
-                echo "Test $test_file is fixed." >&2
-                set fixed (math $fixed + 1)
+                # echo "Test $test_file is broken." >&2
+                set broken (math $broken + 1)
             else
                 # echo "Test $test_file has succeeded." >&2
                 set passed (math $passed + 1)
             end
         else
-            if test -e "$temp_dir/broken"
-                # echo "Test $test_file is broken." >&2
-                set broken (math $broken + 1)
-            else
-                echo "Test $test_file has failed." >&2
+            if test -e "$temp_dir/failure"
+                echo "Test $test_file has failed:" >&2
                 cat "$temp_dir/out" >&2
                 set failed (math $failed + 1)
+            else if test -e "$temp_dir/fixed"
+                echo "Test $test_file is fixed." >&2
+                set fixed (math $fixed + 1)
+            else
+                echo "UNREACHABLE" >&2
+                exit 42
             end
         end
     end
